In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import joblib
from pathlib import Path

In [2]:
# Loading Data
DATA_PATH = Path("data") / "Medicare_DME_Devices_Supplies_by_Supplier_and_Service_2023.csv"
df = pd.read_csv(DATA_PATH, low_memory=False)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28768 entries, 0 to 28767
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Suplr_NPI                  28768 non-null  int64  
 1   Suplr_Prvdr_Last_Name_Org  28768 non-null  object 
 2   Suplr_Prvdr_First_Name     86 non-null     object 
 3   Suplr_Prvdr_MI             35 non-null     object 
 4   Suplr_Prvdr_Crdntls        38 non-null     object 
 5   Suplr_Prvdr_Ent_Cd         28768 non-null  object 
 6   Suplr_Prvdr_St1            28768 non-null  object 
 7   Suplr_Prvdr_St2            4535 non-null   object 
 8   Suplr_Prvdr_City           28768 non-null  object 
 9   Suplr_Prvdr_State_Abrvtn   28768 non-null  object 
 10  Suplr_Prvdr_State_FIPS     28768 non-null  int64  
 11  Suplr_Prvdr_Zip5           28768 non-null  int64  
 12  Suplr_Prvdr_RUCA_Cat       28768 non-null  object 
 13  Suplr_Prvdr_RUCA           28768 non-null  flo

In [4]:
df.head()

Suplr_NPI Suplr_Prvdr_Last_Name_Org Suplr_Prvdr_First_Name Suplr_Prvdr_MI  \
0  1003018359     Jack M Thomas Md Pllc                    NaN            NaN   
1  1003030636                 H-E-B, Lp                    NaN            NaN   
2  1003030636                 H-E-B, Lp                    NaN            NaN   
3  1003030636                 H-E-B, Lp                    NaN            NaN   
4  1003030636                 H-E-B, Lp                    NaN            NaN   

  Suplr_Prvdr_Crdntls Suplr_Prvdr_Ent_Cd              Suplr_Prvdr_St1  \
0                 NaN                  O         4101 Wesley St Ste B   
1                 NaN                  O  2409 E Interstate Highway 2   
2                 NaN                  O  2409 E Interstate Highway 2   
3                 NaN                  O  2409 E Interstate Highway 2   
4                 NaN                  O  2409 E Interstate Highway 2   

  Suplr_Prvdr_St2 Suplr_Prvdr_City Suplr_Prvdr_State_Abrvtn  ...  HCPCS_Cd  \
0             NaN       Greenville                       TX  ...     L1843   
1             NaN          Mission                       TX  ...     A4239   
2             NaN          Mission                       TX  ...     A4253   
3             NaN          Mission                       TX  ...     A4259   
4             NaN          Mission                       TX  ...     J7613   

                                          HCPCS_Desc Suplr_Rentl_Ind  \
0  Knee orthosis, single upright, thigh and calf,...               N   
1  Supply allowance for non-adjunctive, non-impla...               N   
2  Blood glucose test or reagent strips for home ...               N   
3                            Lancets, per box of 100               N   
4  Albuterol, inhalation solution, fda-approved f...               N   

   Tot_Suplr_Benes Tot_Suplr_Clms Tot_Suplr_Srvcs Avg_Suplr_Sbmtd_Chrg  \
0             17.0             17              17          1052.000000   
1              NaN             11              11           152.170000   
2             21.0             44              95            51.031579   
3             13.0             25              30             7.997667   
4              NaN             13            2575             0.337394   

  Avg_Suplr_Mdcr_Alowd_Amt Avg_Suplr_Mdcr_Pymt_Amt Avg_Suplr_Mdcr_Stdzd_Amt  
0              1034.470000              811.030000               800.750000  
1               152.170000               97.992727               216.567273  
2                 8.320000                6.041474                 6.041474  
3                 1.420000                1.005333                 1.005333  
4                 0.033623                0.026369                 0.026357  

[5 rows x 32 columns]

In [5]:
# Dropping the columns
cols_to_drop = [
    "Suplr_Prvdr_First_Name",
    "Suplr_Prvdr_MI",
    "Suplr_Prvdr_Crdntls",
    "Suplr_Prvdr_St2"
]

df.drop(columns=cols_to_drop, inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28768 entries, 0 to 28767
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Suplr_NPI                  28768 non-null  int64  
 1   Suplr_Prvdr_Last_Name_Org  28768 non-null  object 
 2   Suplr_Prvdr_Ent_Cd         28768 non-null  object 
 3   Suplr_Prvdr_St1            28768 non-null  object 
 4   Suplr_Prvdr_City           28768 non-null  object 
 5   Suplr_Prvdr_State_Abrvtn   28768 non-null  object 
 6   Suplr_Prvdr_State_FIPS     28768 non-null  int64  
 7   Suplr_Prvdr_Zip5           28768 non-null  int64  
 8   Suplr_Prvdr_RUCA_Cat       28768 non-null  object 
 9   Suplr_Prvdr_RUCA           28768 non-null  float64
 10  Suplr_Prvdr_RUCA_Desc      28768 non-null  object 
 11  Suplr_Prvdr_Cntry          28768 non-null  object 
 12  Suplr_Prvdr_Spclty_Cd      28768 non-null  object 
 13  Suplr_Prvdr_Spclty_Desc    28768 non-null  obj

In [7]:
# Changing data types:

# Numeric to categorical
cat_cols = ["Suplr_NPI", "Suplr_Prvdr_State_FIPS", "Suplr_Prvdr_Zip5"]

for col in cat_cols:
    df[col] = df[col].astype("category")

# Object to categorical
obj_cols = df.select_dtypes(include="object").columns
df[obj_cols] = df[obj_cols].astype("category")

In [8]:
# Printing data types
print("Data Types:")
print(df.dtypes)

Data Types:
Suplr_NPI                    category
Suplr_Prvdr_Last_Name_Org    category
Suplr_Prvdr_Ent_Cd           category
Suplr_Prvdr_St1              category
Suplr_Prvdr_City             category
Suplr_Prvdr_State_Abrvtn     category
Suplr_Prvdr_State_FIPS       category
Suplr_Prvdr_Zip5             category
Suplr_Prvdr_RUCA_Cat         category
Suplr_Prvdr_RUCA              float64
Suplr_Prvdr_RUCA_Desc        category
Suplr_Prvdr_Cntry            category
Suplr_Prvdr_Spclty_Cd        category
Suplr_Prvdr_Spclty_Desc      category
Suplr_Prvdr_Spclty_Srce      category
RBCS_Lvl                     category
RBCS_Id                      category
RBCS_Desc                    category
HCPCS_Cd                     category
HCPCS_Desc                   category
Suplr_Rentl_Ind              category
Tot_Suplr_Benes               float64
Tot_Suplr_Clms                  int64
Tot_Suplr_Srvcs                 int64
Avg_Suplr_Sbmtd_Chrg          float64
Avg_Suplr_Mdcr_Alowd_Amt      float64


In [9]:
# Identifying missing values
df.isna().sum().sort_values(ascending=False)

Tot_Suplr_Benes              12290
Suplr_NPI                        0
Suplr_Prvdr_Last_Name_Org        0
Avg_Suplr_Mdcr_Pymt_Amt          0
Avg_Suplr_Mdcr_Alowd_Amt         0
Avg_Suplr_Sbmtd_Chrg             0
Tot_Suplr_Srvcs                  0
Tot_Suplr_Clms                   0
Suplr_Rentl_Ind                  0
HCPCS_Desc                       0
HCPCS_Cd                         0
RBCS_Desc                        0
RBCS_Id                          0
RBCS_Lvl                         0
Suplr_Prvdr_Spclty_Srce          0
Suplr_Prvdr_Spclty_Desc          0
Suplr_Prvdr_Spclty_Cd            0
Suplr_Prvdr_Cntry                0
Suplr_Prvdr_RUCA_Desc            0
Suplr_Prvdr_RUCA                 0
Suplr_Prvdr_RUCA_Cat             0
Suplr_Prvdr_Zip5                 0
Suplr_Prvdr_State_FIPS           0
Suplr_Prvdr_State_Abrvtn         0
Suplr_Prvdr_City                 0
Suplr_Prvdr_St1                  0
Suplr_Prvdr_Ent_Cd               0
Avg_Suplr_Mdcr_Stdzd_Amt         0
dtype: int64

In [10]:
# Converting numeric missing value with median
df["Tot_Suplr_Benes"].fillna(df["Tot_Suplr_Benes"].median(), inplace=True)
df["Tot_Suplr_Benes"].isna().sum()

0

In [11]:
# Identifying duplicate values
df.duplicated().sum()

0

In [12]:
# Defining Target variable: High_Risk
risk_cols = [
    'Tot_Suplr_Benes',
    'Tot_Suplr_Srvcs',
    'Avg_Suplr_Sbmtd_Chrg',
    'Avg_Suplr_Mdcr_Alowd_Amt',
    'Avg_Suplr_Mdcr_Pymt_Amt'
]

thresholds = {col: df[col].quantile(0.90) for col in risk_cols}

# Creating high-risk flag: 1 = high-risk, 0 = low-risk
df['High_Risk'] = (
    (df['Tot_Suplr_Benes'] > thresholds['Tot_Suplr_Benes']) |
    (df['Tot_Suplr_Srvcs'] > thresholds['Tot_Suplr_Srvcs']) |
    (df['Avg_Suplr_Sbmtd_Chrg'] > thresholds['Avg_Suplr_Sbmtd_Chrg']) |
    (df['Avg_Suplr_Mdcr_Alowd_Amt'] > thresholds['Avg_Suplr_Mdcr_Alowd_Amt']) |
    (df['Avg_Suplr_Mdcr_Pymt_Amt'] > thresholds['Avg_Suplr_Mdcr_Pymt_Amt'])
).astype(int)

df['High_Risk'].value_counts()

High_Risk
0    20504
1     8264
Name: count, dtype: int64

In [14]:
df.to_csv("final_supplier_dataset.csv", index=False)

In [14]:
# Identify categorical columns
cat_cols = df.select_dtypes(include=['category']).columns.tolist()

# Dictionary to store our mappings for the AI Orchestrator
freq_mappings = {}

# Frequency encoding
for col in cat_cols:
    freq = df[col].value_counts() / len(df)
    freq_mappings[col] = freq.to_dict() 
    df[col + '_freq'] = df[col].map(freq)

# Drop original categorical columns 
df_freq = df.drop(columns=cat_cols)

df_freq.head()

Suplr_Prvdr_RUCA  Tot_Suplr_Benes  Tot_Suplr_Clms  Tot_Suplr_Srvcs  \
0               4.0             17.0              17               17   
1               1.0             26.0              11               11   
2               1.0             21.0              44               95   
3               1.0             13.0              25               30   
4               1.0             26.0              13             2575   

   Avg_Suplr_Sbmtd_Chrg  Avg_Suplr_Mdcr_Alowd_Amt  Avg_Suplr_Mdcr_Pymt_Amt  \
0           1052.000000               1034.470000               811.030000   
1            152.170000                152.170000                97.992727   
2             51.031579                  8.320000                 6.041474   
3              7.997667                  1.420000                 1.005333   
4              0.337394                  0.033623                 0.026369   

   Avg_Suplr_Mdcr_Stdzd_Amt  High_Risk  Suplr_NPI_freq  ...  \
0                800.750000          1        0.000035  ...   
1                216.567273          0        0.000313  ...   
2                  6.041474          0        0.000313  ...   
3                  1.005333          0        0.000313  ...   
4                  0.026357          1        0.000313  ...   

   Suplr_Prvdr_Cntry_freq Suplr_Prvdr_Spclty_Cd_freq  \
0                     1.0                   0.016755   
1                     1.0                   0.250869   
2                     1.0                   0.250869   
3                     1.0                   0.250869   
4                     1.0                   0.250869   

   Suplr_Prvdr_Spclty_Desc_freq  Suplr_Prvdr_Spclty_Srce_freq RBCS_Lvl_freq  \
0                      0.016755                           1.0      0.153608   
1                      0.250869                           1.0      0.625313   
2                      0.250869                           1.0      0.625313   
3                      0.250869                           1.0      0.625313   
4                      0.250869                           1.0      0.063369   

  RBCS_Id_freq  RBCS_Desc_freq HCPCS_Cd_freq HCPCS_Desc_freq  \
0     0.005805        0.153608      0.000939        0.000939   
1     0.167165        0.446538      0.010915        0.010915   
2     0.167165        0.446538      0.096809        0.096809   
3     0.167165        0.446538      0.055513        0.055513   
4     0.048387        0.063369      0.021865        0.021865   

  Suplr_Rentl_Ind_freq  
0             0.822824  
1             0.822824  
2             0.822824  
3             0.822824  
4             0.822824  

[5 rows x 29 columns]

In [15]:
from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df_freq.drop(columns=['High_Risk'])
y = df_freq['High_Risk']

# Splitting into train and temp first
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

# Splitting temp into validation and test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

In [16]:
from sklearn.preprocessing import StandardScaler

# Identify numeric columns
numeric_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Initialize scaler
scaler = StandardScaler()

# Fit on TRAIN only
scaler.fit(X_train[numeric_cols])

# Transform train, val, test
X_train_scaled = X_train.copy()
X_val_scaled = X_val.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.transform(X_train[numeric_cols])
X_val_scaled[numeric_cols] = scaler.transform(X_val[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [17]:
# Create final dataframes
train_scaled_df = pd.concat([X_train_scaled, y_train], axis=1)
val_scaled_df = pd.concat([X_val_scaled, y_val], axis=1)
test_scaled_df = pd.concat([X_test_scaled, y_test], axis=1)

# Save as CSV
train_scaled_df.to_csv("train_scaled.csv", index=False)
val_scaled_df.to_csv("val_scaled.csv", index=False)
test_scaled_df.to_csv("test_scaled.csv", index=False)

In [18]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression

# Use the scaled dataframes you created earlier
X_train = train_scaled_df.drop(columns=['High_Risk'])
y_train = train_scaled_df['High_Risk']

X_val = val_scaled_df.drop(columns=['High_Risk'])
y_val = val_scaled_df['High_Risk']

# Create and fit logistic regression model
log_reg = LogisticRegression(
    penalty='l2',
    solver='lbfgs',
    max_iter=5000,
    class_weight='balanced',
    n_jobs=-1
)

log_reg.fit(X_train, y_train)

# 3) Display basic model info
print("Intercept:", log_reg.intercept_)
print("Number of coefficients:", len(log_reg.coef_[0]))

Intercept: [1.12180955]
Number of coefficients: 28


In [19]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

y_val_pred = log_reg.predict(X_val_scaled)
y_val_proba = log_reg.predict_proba(X_val_scaled)[:, 1]

print("LOGISTIC REGRESSION – VALIDATION RESULTS")
print("Validation Accuracy :", accuracy_score(y_val, y_val_pred))
print("Validation Precision:", precision_score(y_val, y_val_pred, zero_division=0))
print("Validation Recall   :", recall_score(y_val, y_val_pred))
print("Validation F1 Score :", f1_score(y_val, y_val_pred))

print("Validation ROC-AUC  :", roc_auc_score(y_val, y_val_proba))

print("\nConfusion Matrix (Validation):")
print(confusion_matrix(y_val, y_val_pred))

print("\nClassification Report (Validation):")
print(classification_report(y_val, y_val_pred, zero_division=0))

LOGISTIC REGRESSION – VALIDATION RESULTS
Validation Accuracy : 0.8968713789107764
Validation Precision: 0.8341750841750841
Validation Recall   : 0.7998385794995965
Validation F1 Score : 0.8166460651009477
Validation ROC-AUC  : 0.9586973953364379

Confusion Matrix (Validation):
[[2879  197]
 [ 248  991]]

Classification Report (Validation):
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      3076
           1       0.83      0.80      0.82      1239

    accuracy                           0.90      4315
   macro avg       0.88      0.87      0.87      4315
weighted avg       0.90      0.90      0.90      4315



In [20]:
# Features and target from TEST set
X_test = test_scaled_df.drop(columns=['High_Risk'])
y_test = test_scaled_df['High_Risk']

# Predictions on test set
y_pred_test = log_reg.predict(X_test)
y_proba_test = log_reg.predict_proba(X_test)[:, 1]

print("LOGISTIC REGRESSION – TEST RESULTS")
# Evaluation metrics
test_accuracy = accuracy_score(y_test, y_pred_test)
test_precision = precision_score(y_test, y_pred_test)
test_recall = recall_score(y_test, y_pred_test)
test_f1 = f1_score(y_test, y_pred_test)
test_auc = roc_auc_score(y_test, y_proba_test)
test_conf_matrix = confusion_matrix(y_test, y_pred_test)

print("TEST Accuracy:", test_accuracy)
print("TEST Precision:", test_precision)
print("TEST Recall:", test_recall)
print("TEST F1 Score:", test_f1)
print("TEST ROC-AUC:", test_auc)
print("\nConfusion Matrix:\n", test_conf_matrix)

LOGISTIC REGRESSION – TEST RESULTS
TEST Accuracy: 0.8962001853568119
TEST Precision: 0.839622641509434
TEST Recall: 0.7895161290322581
TEST F1 Score: 0.8137988362427265
TEST ROC-AUC: 0.9555672951885565

Confusion Matrix:
 [[2889  187]
 [ 261  979]]


In [21]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier

# Features and target from TRAIN and VALIDATION sets
X_train_rf = train_scaled_df.drop(columns=['High_Risk'])
y_train_rf = train_scaled_df['High_Risk']

X_val_rf = val_scaled_df.drop(columns=['High_Risk'])
y_val_rf = val_scaled_df['High_Risk']

# Create Random Forest model
rf_clf = RandomForestClassifier(
    n_estimators=200,        
    max_depth=10,         
    min_samples_split=20,
    min_samples_leaf=10,
    max_features='sqrt', 
    class_weight='balanced',  
    random_state=42,
    n_jobs=-1                
)

# Fit model
rf_clf.fit(X_train_rf, y_train_rf)

print("Number of features used:", rf_clf.n_features_in_)

Number of features used: 28


In [22]:
# Predictions on validation set
y_val_pred_rf = rf_clf.predict(X_val_rf)
y_val_proba_rf = rf_clf.predict_proba(X_val_rf)[:, 1]

print("VALIDATION RESULTS – RANDOM FOREST")
print("Accuracy :", accuracy_score(y_val_rf, y_val_pred_rf))
print("Precision:", precision_score(y_val_rf, y_val_pred_rf))
print("Recall   :", recall_score(y_val_rf, y_val_pred_rf))
print("F1 Score :", f1_score(y_val_rf, y_val_pred_rf))
print("ROC-AUC  :", roc_auc_score(y_val_rf, y_val_proba_rf))

print("\nConfusion Matrix (Validation):")
print(confusion_matrix(y_val_rf, y_val_pred_rf))

print("\nClassification Report (Validation):")
print(classification_report(y_val_rf, y_val_pred_rf))

VALIDATION RESULTS – RANDOM FOREST
Accuracy : 0.9986095017381228
Precision: 0.99597747385358
Recall   : 0.9991928974979822
F1 Score : 0.9975825946817083
ROC-AUC  : 0.999996064194561

Confusion Matrix (Validation):
[[3071    5]
 [   1 1238]]

Classification Report (Validation):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3076
           1       1.00      1.00      1.00      1239

    accuracy                           1.00      4315
   macro avg       1.00      1.00      1.00      4315
weighted avg       1.00      1.00      1.00      4315



In [23]:
# Features and target from TEST set
X_test = test_scaled_df.drop(columns=['High_Risk'])
y_test = test_scaled_df['High_Risk']

# Predictions on test set
y_pred_test_rf = rf_clf.predict(X_test)
y_proba_test_rf = rf_clf.predict_proba(X_test)[:, 1]

# Evaluation metrics
test_accuracy_rf = accuracy_score(y_test, y_pred_test_rf)
test_precision_rf = precision_score(y_test, y_pred_test_rf)
test_recall_rf = recall_score(y_test, y_pred_test_rf)
test_f1_rf = f1_score(y_test, y_pred_test_rf)
test_auc_rf = roc_auc_score(y_test, y_proba_test_rf)
test_conf_matrix_rf = confusion_matrix(y_test, y_pred_test_rf)

print("RANDOM FOREST – TEST RESULTS")
print("Accuracy :", test_accuracy_rf)
print("Precision:", test_precision_rf)
print("Recall   :", test_recall_rf)
print("F1 Score :", test_f1_rf)
print("ROC-AUC  :", test_auc_rf)
print("\nConfusion Matrix:\n", test_conf_matrix_rf)

print("\nClassification Report (Test):")
print(classification_report(y_test, y_pred_test_rf))

RANDOM FOREST – TEST RESULTS
Accuracy : 0.9993049119555144
Precision: 0.997586484312148
Recall   : 1.0
F1 Score : 0.9987917841320982
ROC-AUC  : 0.999988202105793

Confusion Matrix:
 [[3073    3]
 [   0 1240]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3076
           1       1.00      1.00      1.00      1240

    accuracy                           1.00      4316
   macro avg       1.00      1.00      1.00      4316
weighted avg       1.00      1.00      1.00      4316



In [24]:
from sklearn.ensemble import StackingClassifier

# Splitting features and target from scaled dataframes 
X_train = train_scaled_df.drop(columns=['High_Risk'])
y_train = train_scaled_df['High_Risk']

X_val = val_scaled_df.drop(columns=['High_Risk'])
y_val = val_scaled_df['High_Risk']

X_test = test_scaled_df.drop(columns=['High_Risk'])
y_test = test_scaled_df['High_Risk']

# Defining base models 
base_estimators = [
    (
        "log_reg_base",
        LogisticRegression(
            penalty="l2",
            solver="lbfgs",
            max_iter=5000,
            class_weight="balanced",
            n_jobs=-1
        )
    ),
    (
        "rf_base",
        RandomForestClassifier(
            n_estimators=300,
            max_depth=None,
            min_samples_split=2,
            min_samples_leaf=1,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1
        )
    )
]

# Defining stacked model
stack_clf = StackingClassifier(
    estimators=base_estimators,
    final_estimator=LogisticRegression(
        penalty="l2",
        solver="lbfgs",
        max_iter=5000,
        class_weight="balanced",
        n_jobs=-1
    ),
    stack_method="predict_proba",  
    n_jobs=-1
)

# Fitting on TRAIN only 
stack_clf.fit(X_train, y_train)

StackingClassifier(estimators=[('log_reg_base',
                                LogisticRegression(class_weight='balanced',
                                                   max_iter=5000, n_jobs=-1)),
                               ('rf_base',
                                RandomForestClassifier(class_weight='balanced',
                                                       n_estimators=300,
                                                       n_jobs=-1,
                                                       random_state=42))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=5000,
                                                      n_jobs=-1),
                   n_jobs=-1, stack_method='predict_proba')

In [25]:
# Validation predictions 
y_val_pred_stack = stack_clf.predict(X_val)
y_val_proba_stack = stack_clf.predict_proba(X_val)[:, 1]

print("STACKED MODEL – VALIDATION RESULTS")
print("Accuracy :", accuracy_score(y_val, y_val_pred_stack))
print("Precision:", precision_score(y_val, y_val_pred_stack))
print("Recall   :", recall_score(y_val, y_val_pred_stack))
print("F1 Score :", f1_score(y_val, y_val_pred_stack))
print("ROC-AUC  :", roc_auc_score(y_val, y_val_proba_stack))

print("\nConfusion Matrix (Validation):")
print(confusion_matrix(y_val, y_val_pred_stack))

print("\nClassification Report (Validation):")
print(classification_report(y_val, y_val_pred_stack))

STACKED MODEL – VALIDATION RESULTS
Accuracy : 0.9995365005793743
Precision: 0.9991928974979822
Recall   : 0.9991928974979822
F1 Score : 0.9991928974979822
ROC-AUC  : 0.9999986880648537

Confusion Matrix (Validation):
[[3075    1]
 [   1 1238]]

Classification Report (Validation):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3076
           1       1.00      1.00      1.00      1239

    accuracy                           1.00      4315
   macro avg       1.00      1.00      1.00      4315
weighted avg       1.00      1.00      1.00      4315



In [26]:
# Test predictions 
y_test_pred_stack = stack_clf.predict(X_test)
y_test_proba_stack = stack_clf.predict_proba(X_test)[:, 1]

print("STACKED MODEL – TEST RESULTS")
print("Accuracy :", accuracy_score(y_test, y_test_pred_stack))
print("Precision:", precision_score(y_test, y_test_pred_stack))
print("Recall   :", recall_score(y_test, y_test_pred_stack))
print("F1 Score :", f1_score(y_test, y_test_pred_stack))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_proba_stack))

print("\nConfusion Matrix (Test):")
print(confusion_matrix(y_test, y_test_pred_stack))

print("\nClassification Report (Test):")
print(classification_report(y_test, y_test_pred_stack))


STACKED MODEL – TEST RESULTS
Accuracy : 0.9995366079703429
Precision: 0.9991935483870967
Recall   : 0.9991935483870967
F1 Score : 0.9991935483870967
ROC-AUC  : 0.9999981647720122

Confusion Matrix (Test):
[[3075    1]
 [   1 1239]]

Classification Report (Test):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3076
           1       1.00      1.00      1.00      1240

    accuracy                           1.00      4316
   macro avg       1.00      1.00      1.00      4316
weighted avg       1.00      1.00      1.00      4316



In [27]:
# Create models directory if it doesn't exist
MODEL_DIR = Path("models")
MODEL_DIR.mkdir(exist_ok=True)

In [28]:
# Save models
joblib.dump(freq_mappings, MODEL_DIR / "freq_mappings.pkl")
joblib.dump(log_reg, MODEL_DIR / "logistic_regression.pkl")
joblib.dump(rf_clf, MODEL_DIR / "random_forest.pkl")
joblib.dump(stack_clf, MODEL_DIR / "stacking_model.pkl")

['models\\stacking_model.pkl']

In [29]:
# Save scaler
joblib.dump(scaler, MODEL_DIR / "scaler.pkl")

['models\\scaler.pkl']

In [30]:
# Save feature list
joblib.dump(X_train.columns.tolist(), MODEL_DIR / "feature_columns.pkl")

['models\\feature_columns.pkl']

In [31]:
# Identify numeric columns in original X_train (before scaling)
numeric_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Compute median for each numeric column
median_values = X_train[numeric_cols].median().to_dict()

joblib.dump(median_values, MODEL_DIR / "median_values.pkl")

['models\\median_values.pkl']

In [27]:
# Filter high-risk suppliers
df_hr = df[df["High_Risk"] == 1].copy()

# Define risk columns
risk_cols = [
    "Tot_Suplr_Benes",
    "Tot_Suplr_Srvcs",
    "Avg_Suplr_Sbmtd_Chrg",
    "Avg_Suplr_Mdcr_Alowd_Amt",
    "Avg_Suplr_Mdcr_Pymt_Amt"
]

# Create a combined risk score
df_hr["risk_score"] = df_hr[risk_cols].sum(axis=1)

# Sort by risk_score descending
df_hr = df_hr.sort_values(by="risk_score", ascending=False)

# Show top 3 suppliers
top3 = df_hr.head(3)
print(top3[["Suplr_Prvdr_Last_Name_Org", "Suplr_Prvdr_City", "risk_score"]])

                       Suplr_Prvdr_Last_Name_Org Suplr_Prvdr_City  \
25565              Pretty In Pink Boutique, Inc.          El Paso   
4673   Konaniah Medical Equipment & Supplies Llc    Grand Prairie   
25564              Pretty In Pink Boutique, Inc.          El Paso   

         risk_score  
25565  5.437109e+07  
4673   2.493954e+07  
25564  5.474260e+06  
